// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_GET_6.Server.Data;

#nullable disable

namespace Project_GET_6.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20230419214228_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_GET_6.Shared.Project", b =>
                {
                    b.Property<string>("ProjectCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectManagerUsername")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectCode");

                    b.HasIndex("ProjectManagerUsername");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            ProjectCode = "P1A",
                            ProjectManagerUsername = "mika123",
                            ProjectName = "Test1"
                        },
                        new
                        {
                            ProjectCode = "P2A",
                            ProjectManagerUsername = "mika123",
                            ProjectName = "Test2"
                        },
                        new
                        {
                            ProjectCode = "P3B",
                            ProjectManagerUsername = "mika123",
                            ProjectName = "Test3"
                        });
                });

            modelBuilder.Entity("Project_GET_6.Shared.ProjectTask", b =>
                {
                    b.Property<int>("ProjectTaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProjectTaskId"));

                    b.Property<string>("AssigneeUsername")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Deadline")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ParentProjectProjectCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<double>("Progress")
                        .HasColumnType("float");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("ProjectTaskId");

                    b.HasIndex("AssigneeUsername");

                    b.HasIndex("ParentProjectProjectCode");

                    b.ToTable("ProjectTasks");

                    b.HasData(
                        new
                        {
                            ProjectTaskId = 1,
                            AssigneeUsername = "zika123",
                            Deadline = new DateTime(2023, 4, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Project Test1 Task 1",
                            ParentProjectProjectCode = "P1A",
                            Progress = 0.0,
                            Status = 0
                        },
                        new
                        {
                            ProjectTaskId = 2,
                            AssigneeUsername = "zika123",
                            Deadline = new DateTime(2023, 4, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Project Test1 Task 2",
                            ParentProjectProjectCode = "P2A",
                            Progress = 0.0,
                            Status = 0
                        },
                        new
                        {
                            ProjectTaskId = 3,
                            AssigneeUsername = "zika123",
                            Deadline = new DateTime(2023, 4, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Project Test1 Task 3",
                            ParentProjectProjectCode = "P3B",
                            Progress = 0.0,
                            Status = 0
                        },
                        new
                        {
                            ProjectTaskId = 4,
                            AssigneeUsername = "aca123",
                            Deadline = new DateTime(2023, 4, 19, 0, 0, 0, 0, DateTimeKind.Local),
                            Description = "Project Test2 Task 1",
                            ParentProjectProjectCode = "P1A",
                            Progress = 0.0,
                            Status = 0
                        });
                });

            modelBuilder.Entity("Project_GET_6.Shared.Role", b =>
                {
                    b.Property<int?>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int?>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 0,
                            RoleName = "None"
                        },
                        new
                        {
                            RoleId = 1,
                            RoleName = "Developer"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Project Manager"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Administrator"
                        });
                });

            modelBuilder.Entity("Project_GET_6.Shared.User", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Username");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Username = "pera123",
                            Email = "pera123@mail.com",
                            Name = "Petar",
                            Password = "pera123",
                            RoleId = 3,
                            Surname = "Petrovic"
                        },
                        new
                        {
                            Username = "mika123",
                            Email = "mika123@mail.com",
                            Name = "Milan",
                            Password = "mika123",
                            RoleId = 2,
                            Surname = "Milanovic"
                        },
                        new
                        {
                            Username = "zika123",
                            Email = "zika123@mail.com",
                            Name = "Zivanko",
                            Password = "zika123",
                            RoleId = 1,
                            Surname = "Zivankovic"
                        },
                        new
                        {
                            Username = "nidza123",
                            Email = "nidza123@mail.com",
                            Name = "Nikola",
                            Password = "nidza123",
                            RoleId = 1,
                            Surname = "Nikolic"
                        },
                        new
                        {
                            Username = "aca123",
                            Email = "aca123@mail.com",
                            Name = "Aleksandar",
                            Password = "aca123",
                            RoleId = 1,
                            Surname = "Aleksandrovic"
                        });
                });

            modelBuilder.Entity("Project_GET_6.Shared.Project", b =>
                {
                    b.HasOne("Project_GET_6.Shared.User", "ProjectManager")
                        .WithMany()
                        .HasForeignKey("ProjectManagerUsername")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProjectManager");
                });

            modelBuilder.Entity("Project_GET_6.Shared.ProjectTask", b =>
                {
                    b.HasOne("Project_GET_6.Shared.User", "Assignee")
                        .WithMany()
                        .HasForeignKey("AssigneeUsername");

                    b.HasOne("Project_GET_6.Shared.Project", "ParentProject")
                        .WithMany()
                        .HasForeignKey("ParentProjectProjectCode");

                    b.Navigation("Assignee");

                    b.Navigation("ParentProject");
                });

            modelBuilder.Entity("Project_GET_6.Shared.User", b =>
                {
                    b.HasOne("Project_GET_6.Shared.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });
#pragma warning restore 612, 618
        }
    }
}
